server:
    port: 8082

logging:
    level:
        io:
            reflectoring: DEBUG
        org:
            springframework:
                data:
                    r2dbc: DEBUG

spring:
   webflux:
       base-path: /api

   r2dbc:
      url: r2dbc:postgresql://postgres_user:S3cret@localhost:5432/postgres_db

   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
       jdbc:
         lob:
           non_contextual_creation: true

     hibernate:
       ddl-auto: create-drop
# spring.r2dbc.url=r2dbc:postgresql://postgres:postgres@localhost:5432/postgres
# spring.r2dbc.pool.enabled=true
# spring.r2dbc.pool.initial-size=5
# spring.r2dbc.pool.max-size=10
# logging.level.org.springframework.r2dbc=DEBUG
# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/postgres_db
#     username: postgres_user
#     password: S3cret